### ISSUE TITLE
Error in Column density plots when using logarithmic colour bar. 

### ISSUE THREAD

**Issue by AdamFenton** [dmentipl/plonk#31] opened 2020-12-02 14:35 UTC
### Describe the bug

Using the image(quanity='density') method to produce integrated density plots with a logarithmic colour bar causes artefact in regions of a disc where there are no particles. The minimum density colour does not extend to the edges of the box or fill in the gap around the sink 

### To Reproduce

```python
import plonk
snap = plonk.load_snap('disc_00010.h5')
units = {'position': 'au', 'density': 'g/cm^3', 'projection': 'cm'}
snap.image(
... quantity='density',
... extent=(-120,120,-120,120),
... units=units,
... norm='log',
... vmin=1,
... vmax=3000,
... )
plt.show()
```
No error is produced, the plot is produced successfully but does not look correct when using the norm='log' option.

### Expected behaviour

Expected the plotted area to be filled with the colour corresponding to vmin 

### Screenshots 

![Figure_1](https://user-images.githubusercontent.com/54849364/100886103-4fee4780-34ab-11eb-80db-1d76d2d09bd7.png)
### Examples
Use the attached .h5 file with plonk (code above) to reproduce problem 

### Environment

+ OS: MacOS Catalina 10.15.7 
+ Python: Python 3.8.6
+ Plonk version: plonk 0.7.3

### Data source

[disc_00010.h5.zip](https://github.com/dmentipl/plonk/files/5629895/disc_00010.h5.zip)

**Comment by dmentipl** [comment] 2021-03-12 06:31
Hi @AdamFenton, thanks for raising this issue, and sorry for the long delay in my response!

The issue is that in those regions the density is identically zero (computed by the SPH interpolation routines). So taking a log is not possible. This is an issue in matplotlib. It's not a bug per se but a choice. You can reproduce this with

```python
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

arr = np.linspace(0, 10, 25).reshape([5, 5])
norm = mpl.colors.LogNorm()
plt.imshow(arr, norm=norm)
```

![Figure_1](https://user-images.githubusercontent.com/8281189/110901370-59b00280-8358-11eb-8cc9-c30668d45b1c.png)

Notice the top left corner is white.

So, we could change this in Plonk from the default matplotlib behaviour. An alternative is to use the [`SymLogNorm`](https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.SymLogNorm.html) but this is not quite the same.

Let me know what you think. I'm happy to take suggestions and (or course) contributions.

**Comment by dmentipl** [comment] 2021-04-16 07:59
Hi @AdamFenton, I'm going to close this issue. Please feel free to re-open it if you'd like to suggest any particular changes.

**Closed by dmentipl** 2021-04-16 07:59 UTC
